/* automatically generated by rust-bindgen 0.73.2 */

// Generated by scripts/gen-bindings.sh from X-Plane SDK 4.3.0. Do not edit.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code, clippy::all)]

pub const XPLM_NO_PLUGIN_ID: i32 = -1;
pub const XPLM_PLUGIN_XPLANE: i32 = 0;
pub const kXPLM_Version: i32 = 430;
pub const XPLM_KEY_RETURN: i32 = 13;
pub const XPLM_KEY_ESCAPE: i32 = 27;
pub const XPLM_KEY_TAB: i32 = 9;
pub const XPLM_KEY_DELETE: i32 = 8;
pub const XPLM_KEY_LEFT: i32 = 28;
pub const XPLM_KEY_RIGHT: i32 = 29;
pub const XPLM_KEY_UP: i32 = 30;
pub const XPLM_KEY_DOWN: i32 = 31;
pub const XPLM_KEY_0: i32 = 48;
pub const XPLM_KEY_1: i32 = 49;
pub const XPLM_KEY_2: i32 = 50;
pub const XPLM_KEY_3: i32 = 51;
pub const XPLM_KEY_4: i32 = 52;
pub const XPLM_KEY_5: i32 = 53;
pub const XPLM_KEY_6: i32 = 54;
pub const XPLM_KEY_7: i32 = 55;
pub const XPLM_KEY_8: i32 = 56;
pub const XPLM_KEY_9: i32 = 57;
pub const XPLM_KEY_DECIMAL: i32 = 46;
pub const XPLM_VK_BACK: i32 = 8;
pub const XPLM_VK_TAB: i32 = 9;
pub const XPLM_VK_CLEAR: i32 = 12;
pub const XPLM_VK_RETURN: i32 = 13;
pub const XPLM_VK_ESCAPE: i32 = 27;
pub const XPLM_VK_SPACE: i32 = 32;
pub const XPLM_VK_PRIOR: i32 = 33;
pub const XPLM_VK_NEXT: i32 = 34;
pub const XPLM_VK_END: i32 = 35;
pub const XPLM_VK_HOME: i32 = 36;
pub const XPLM_VK_LEFT: i32 = 37;
pub const XPLM_VK_UP: i32 = 38;
pub const XPLM_VK_RIGHT: i32 = 39;
pub const XPLM_VK_DOWN: i32 = 40;
pub const XPLM_VK_SELECT: i32 = 41;
pub const XPLM_VK_PRINT: i32 = 42;
pub const XPLM_VK_EXECUTE: i32 = 43;
pub const XPLM_VK_SNAPSHOT: i32 = 44;
pub const XPLM_VK_INSERT: i32 = 45;
pub const XPLM_VK_DELETE: i32 = 46;
pub const XPLM_VK_HELP: i32 = 47;
pub const XPLM_VK_0: i32 = 48;
pub const XPLM_VK_1: i32 = 49;
pub const XPLM_VK_2: i32 = 50;
pub const XPLM_VK_3: i32 = 51;
pub const XPLM_VK_4: i32 = 52;
pub const XPLM_VK_5: i32 = 53;
pub const XPLM_VK_6: i32 = 54;
pub const XPLM_VK_7: i32 = 55;
pub const XPLM_VK_8: i32 = 56;
pub const XPLM_VK_9: i32 = 57;
pub const XPLM_VK_A: i32 = 65;
pub const XPLM_VK_B: i32 = 66;
pub const XPLM_VK_C: i32 = 67;
pub const XPLM_VK_D: i32 = 68;
pub const XPLM_VK_E: i32 = 69;
pub const XPLM_VK_F: i32 = 70;
pub const XPLM_VK_G: i32 = 71;
pub const XPLM_VK_H: i32 = 72;
pub const XPLM_VK_I: i32 = 73;
pub const XPLM_VK_J: i32 = 74;
pub const XPLM_VK_K: i32 = 75;
pub const XPLM_VK_L: i32 = 76;
pub const XPLM_VK_M: i32 = 77;
pub const XPLM_VK_N: i32 = 78;
pub const XPLM_VK_O: i32 = 79;
pub const XPLM_VK_P: i32 = 80;
pub const XPLM_VK_Q: i32 = 81;
pub const XPLM_VK_R: i32 = 82;
pub const XPLM_VK_S: i32 = 83;
pub const XPLM_VK_T: i32 = 84;
pub const XPLM_VK_U: i32 = 85;
pub const XPLM_VK_V: i32 = 86;
pub const XPLM_VK_W: i32 = 87;
pub const XPLM_VK_X: i32 = 88;
pub const XPLM_VK_Y: i32 = 89;
pub const XPLM_VK_Z: i32 = 90;
pub const XPLM_VK_NUMPAD0: i32 = 96;
pub const XPLM_VK_NUMPAD1: i32 = 97;
pub const XPLM_VK_NUMPAD2: i32 = 98;
pub const XPLM_VK_NUMPAD3: i32 = 99;
pub const XPLM_VK_NUMPAD4: i32 = 100;
pub const XPLM_VK_NUMPAD5: i32 = 101;
pub const XPLM_VK_NUMPAD6: i32 = 102;
pub const XPLM_VK_NUMPAD7: i32 = 103;
pub const XPLM_VK_NUMPAD8: i32 = 104;
pub const XPLM_VK_NUMPAD9: i32 = 105;
pub const XPLM_VK_MULTIPLY: i32 = 106;
pub const XPLM_VK_ADD: i32 = 107;
pub const XPLM_VK_SEPARATOR: i32 = 108;
pub const XPLM_VK_SUBTRACT: i32 = 109;
pub const XPLM_VK_DECIMAL: i32 = 110;
pub const XPLM_VK_DIVIDE: i32 = 111;
pub const XPLM_VK_F1: i32 = 112;
pub const XPLM_VK_F2: i32 = 113;
pub const XPLM_VK_F3: i32 = 114;
pub const XPLM_VK_F4: i32 = 115;
pub const XPLM_VK_F5: i32 = 116;
pub const XPLM_VK_F6: i32 = 117;
pub const XPLM_VK_F7: i32 = 118;
pub const XPLM_VK_F8: i32 = 119;
pub const XPLM_VK_F9: i32 = 120;
pub const XPLM_VK_F10: i32 = 121;
pub const XPLM_VK_F11: i32 = 122;
pub const XPLM_VK_F12: i32 = 123;
pub const XPLM_VK_F13: i32 = 124;
pub const XPLM_VK_F14: i32 = 125;
pub const XPLM_VK_F15: i32 = 126;
pub const XPLM_VK_F16: i32 = 127;
pub const XPLM_VK_F17: i32 = 128;
pub const XPLM_VK_F18: i32 = 129;
pub const XPLM_VK_F19: i32 = 130;
pub const XPLM_VK_F20: i32 = 131;
pub const XPLM_VK_F21: i32 = 132;
pub const XPLM_VK_F22: i32 = 133;
pub const XPLM_VK_F23: i32 = 134;
pub const XPLM_VK_F24: i32 = 135;
pub const XPLM_VK_EQUAL: i32 = 176;
pub const XPLM_VK_MINUS: i32 = 177;
pub const XPLM_VK_RBRACE: i32 = 178;
pub const XPLM_VK_LBRACE: i32 = 179;
pub const XPLM_VK_QUOTE: i32 = 180;
pub const XPLM_VK_SEMICOLON: i32 = 181;
pub const XPLM_VK_BACKSLASH: i32 = 182;
pub const XPLM_VK_COMMA: i32 = 183;
pub const XPLM_VK_SLASH: i32 = 184;
pub const XPLM_VK_PERIOD: i32 = 185;
pub const XPLM_VK_BACKQUOTE: i32 = 186;
pub const XPLM_VK_ENTER: i32 = 187;
pub const XPLM_VK_NUMPAD_ENT: i32 = 188;
pub const XPLM_VK_NUMPAD_EQ: i32 = 189;
pub const XPLM_USER_AIRCRAFT: i32 = 0;
pub const XPLM_MSG_PLANE_CRASHED: i32 = 101;
pub const XPLM_MSG_PLANE_LOADED: i32 = 102;
pub const XPLM_MSG_AIRPORT_LOADED: i32 = 103;
pub const XPLM_MSG_SCENERY_LOADED: i32 = 104;
pub const XPLM_MSG_AIRPLANE_COUNT_CHANGED: i32 = 105;
pub const XPLM_MSG_PLANE_UNLOADED: i32 = 106;
pub const XPLM_MSG_WILL_WRITE_PREFS: i32 = 107;
pub const XPLM_MSG_LIVERY_LOADED: i32 = 108;
pub const XPLM_MSG_ENTERED_VR: i32 = 109;
pub const XPLM_MSG_EXITING_VR: i32 = 110;
pub const XPLM_MSG_RELEASE_PLANES: i32 = 111;
pub const XPLM_MSG_FMOD_BANK_LOADED: i32 = 112;
pub const XPLM_MSG_FMOD_BANK_UNLOADING: i32 = 113;
pub const XPLM_MSG_DATAREFS_ADDED: i32 = 114;
pub type XPLMPluginID = ::std::os::raw::c_int;
pub const xplm_ShiftFlag: _bindgen_ty_1 = 1;
pub const xplm_OptionAltFlag: _bindgen_ty_1 = 2;
pub const xplm_ControlFlag: _bindgen_ty_1 = 4;
pub const xplm_DownFlag: _bindgen_ty_1 = 8;
pub const xplm_UpFlag: _bindgen_ty_1 = 16;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
pub type XPLMKeyFlags = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMFixedString150_t {
    pub buffer: [::std::os::raw::c_char; 150usize],
}
pub const xplm_CursorDefault: _bindgen_ty_2 = 0;
pub const xplm_CursorHidden: _bindgen_ty_2 = 1;
pub const xplm_CursorArrow: _bindgen_ty_2 = 2;
pub const xplm_CursorCustom: _bindgen_ty_2 = 3;
pub const xplm_CursorRotateSmall: _bindgen_ty_2 = 4;
pub const xplm_CursorRotateSmallLeft: _bindgen_ty_2 = 5;
pub const xplm_CursorRotateSmallRight: _bindgen_ty_2 = 6;
pub const xplm_CursorRotateMedium: _bindgen_ty_2 = 7;
pub const xplm_CursorRotateMediumLeft: _bindgen_ty_2 = 8;
pub const xplm_CursorRotateMediumRight: _bindgen_ty_2 = 9;
pub const xplm_CursorRotateLarge: _bindgen_ty_2 = 10;
pub const xplm_CursorRotateLargeLeft: _bindgen_ty_2 = 11;
pub const xplm_CursorRotateLargeRight: _bindgen_ty_2 = 12;
pub const xplm_CursorUpDown: _bindgen_ty_2 = 13;
pub const xplm_CursorDown: _bindgen_ty_2 = 14;
pub const xplm_CursorUp: _bindgen_ty_2 = 15;
pub const xplm_CursorLeftRight: _bindgen_ty_2 = 16;
pub const xplm_CursorLeft: _bindgen_ty_2 = 17;
pub const xplm_CursorRight: _bindgen_ty_2 = 18;
pub const xplm_CursorButton: _bindgen_ty_2 = 19;
pub const xplm_CursorHandle: _bindgen_ty_2 = 20;
pub const xplm_CursorFourArrows: _bindgen_ty_2 = 21;
pub const xplm_CursorSplitterH: _bindgen_ty_2 = 22;
pub const xplm_CursorSplitterV: _bindgen_ty_2 = 23;
pub const xplm_CursorText: _bindgen_ty_2 = 24;
pub type _bindgen_ty_2 = ::std::os::raw::c_uint;
pub type XPLMCursorStatus = ::std::os::raw::c_int;
pub const xplm_MouseDown: _bindgen_ty_3 = 1;
pub const xplm_MouseDrag: _bindgen_ty_3 = 2;
pub const xplm_MouseUp: _bindgen_ty_3 = 3;
pub type _bindgen_ty_3 = ::std::os::raw::c_uint;
pub type XPLMMouseStatus = ::std::os::raw::c_int;
pub const xplm_ControlCameraUntilViewChanges: _bindgen_ty_4 = 1;
pub const xplm_ControlCameraForever: _bindgen_ty_4 = 2;
pub type _bindgen_ty_4 = ::std::os::raw::c_uint;
pub type XPLMCameraControlDuration = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMCameraPosition_t {
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub pitch: f32,
    pub heading: f32,
    pub roll: f32,
    pub zoom: f32,
}
pub type XPLMCameraControl_f = ::std::option::Option<
    unsafe extern "C" fn(
        outCameraPosition: *mut XPLMCameraPosition_t,
        inIsLosingControl: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn XPLMControlCamera(
        inHowLong: XPLMCameraControlDuration,
        inControlFunc: XPLMCameraControl_f,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn XPLMDontControlCamera();
}
unsafe extern "C" {
    pub fn XPLMIsCameraBeingControlled(
        outCameraControlDuration: *mut XPLMCameraControlDuration,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMReadCameraPosition(outCameraPosition: *mut XPLMCameraPosition_t);
}
pub type XPLMDataRef = *mut ::std::os::raw::c_void;
pub type XPLMDataTypeID = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn XPLMCountDataRefs() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMGetDataRefsByIndex(
        offset: ::std::os::raw::c_int,
        count: ::std::os::raw::c_int,
        outDataRefs: *mut XPLMDataRef,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMDataRefInfo_t {
    pub structSize: ::std::os::raw::c_int,
    pub name: *const ::std::os::raw::c_char,
    pub type_: XPLMDataTypeID,
    pub writable: ::std::os::raw::c_int,
    pub owner: XPLMPluginID,
}
unsafe extern "C" {
    pub fn XPLMGetDataRefInfo(inDataRef: XPLMDataRef, outInfo: *mut XPLMDataRefInfo_t);
}
unsafe extern "C" {
    pub fn XPLMFindDataRef(inDataRefName: *const ::std::os::raw::c_char) -> XPLMDataRef;
}
unsafe extern "C" {
    pub fn XPLMCanWriteDataRef(inDataRef: XPLMDataRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMIsDataRefGood(inDataRef: XPLMDataRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMGetDataRefTypes(inDataRef: XPLMDataRef) -> XPLMDataTypeID;
}
unsafe extern "C" {
    pub fn XPLMGetDatai(inDataRef: XPLMDataRef) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSetDatai(inDataRef: XPLMDataRef, inValue: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn XPLMGetDataf(inDataRef: XPLMDataRef) -> f32;
}
unsafe extern "C" {
    pub fn XPLMSetDataf(inDataRef: XPLMDataRef, inValue: f32);
}
unsafe extern "C" {
    pub fn XPLMGetDatad(inDataRef: XPLMDataRef) -> f64;
}
unsafe extern "C" {
    pub fn XPLMSetDatad(inDataRef: XPLMDataRef, inValue: f64);
}
unsafe extern "C" {
    pub fn XPLMGetDatavi(
        inDataRef: XPLMDataRef,
        outValues: *mut ::std::os::raw::c_int,
        inOffset: ::std::os::raw::c_int,
        inMax: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSetDatavi(
        inDataRef: XPLMDataRef,
        inValues: *mut ::std::os::raw::c_int,
        inoffset: ::std::os::raw::c_int,
        inCount: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetDatavf(
        inDataRef: XPLMDataRef,
        outValues: *mut f32,
        inOffset: ::std::os::raw::c_int,
        inMax: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSetDatavf(
        inDataRef: XPLMDataRef,
        inValues: *mut f32,
        inoffset: ::std::os::raw::c_int,
        inCount: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetDatab(
        inDataRef: XPLMDataRef,
        outValue: *mut ::std::os::raw::c_void,
        inOffset: ::std::os::raw::c_int,
        inMaxBytes: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSetDatab(
        inDataRef: XPLMDataRef,
        inValue: *mut ::std::os::raw::c_void,
        inOffset: ::std::os::raw::c_int,
        inLength: ::std::os::raw::c_int,
    );
}
pub type XPLMGetDatai_f = ::std::option::Option<
    unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void) -> ::std::os::raw::c_int,
>;
pub type XPLMSetDatai_f = ::std::option::Option<
    unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void, inValue: ::std::os::raw::c_int),
>;
pub type XPLMGetDataf_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void) -> f32>;
pub type XPLMSetDataf_f = ::std::option::Option<
    unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void, inValue: f32),
>;
pub type XPLMGetDatad_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void) -> f64>;
pub type XPLMSetDatad_f = ::std::option::Option<
    unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void, inValue: f64),
>;
pub type XPLMGetDatavi_f = ::std::option::Option<
    unsafe extern "C" fn(
        inRefcon: *mut ::std::os::raw::c_void,
        outValues: *mut ::std::os::raw::c_int,
        inOffset: ::std::os::raw::c_int,
        inMax: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMSetDatavi_f = ::std::option::Option<
    unsafe extern "C" fn(
        inRefcon: *mut ::std::os::raw::c_void,
        inValues: *mut ::std::os::raw::c_int,
        inOffset: ::std::os::raw::c_int,
        inCount: ::std::os::raw::c_int,
    ),
>;
pub type XPLMGetDatavf_f = ::std::option::Option<
    unsafe extern "C" fn(
        inRefcon: *mut ::std::os::raw::c_void,
        outValues: *mut f32,
        inOffset: ::std::os::raw::c_int,
        inMax: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMSetDatavf_f = ::std::option::Option<
    unsafe extern "C" fn(
        inRefcon: *mut ::std::os::raw::c_void,
        inValues: *mut f32,
        inOffset: ::std::os::raw::c_int,
        inCount: ::std::os::raw::c_int,
    ),
>;
pub type XPLMGetDatab_f = ::std::option::Option<
    unsafe extern "C" fn(
        inRefcon: *mut ::std::os::raw::c_void,
        outValue: *mut ::std::os::raw::c_void,
        inOffset: ::std::os::raw::c_int,
        inMaxLength: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMSetDatab_f = ::std::option::Option<
    unsafe extern "C" fn(
        inRefcon: *mut ::std::os::raw::c_void,
        inValue: *mut ::std::os::raw::c_void,
        inOffset: ::std::os::raw::c_int,
        inLength: ::std::os::raw::c_int,
    ),
>;
unsafe extern "C" {
    pub fn XPLMRegisterDataAccessor(
        inDataName: *const ::std::os::raw::c_char,
        inDataType: XPLMDataTypeID,
        inIsWritable: ::std::os::raw::c_int,
        inReadInt: XPLMGetDatai_f,
        inWriteInt: XPLMSetDatai_f,
        inReadFloat: XPLMGetDataf_f,
        inWriteFloat: XPLMSetDataf_f,
        inReadDouble: XPLMGetDatad_f,
        inWriteDouble: XPLMSetDatad_f,
        inReadIntArray: XPLMGetDatavi_f,
        inWriteIntArray: XPLMSetDatavi_f,
        inReadFloatArray: XPLMGetDatavf_f,
        inWriteFloatArray: XPLMSetDatavf_f,
        inReadData: XPLMGetDatab_f,
        inWriteData: XPLMSetDatab_f,
        inReadRefcon: *mut ::std::os::raw::c_void,
        inWriteRefcon: *mut ::std::os::raw::c_void,
    ) -> XPLMDataRef;
}
unsafe extern "C" {
    pub fn XPLMUnregisterDataAccessor(inDataRef: XPLMDataRef);
}
pub type XPLMDataChanged_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void)>;
unsafe extern "C" {
    pub fn XPLMShareData(
        inDataName: *const ::std::os::raw::c_char,
        inDataType: XPLMDataTypeID,
        inNotificationFunc: XPLMDataChanged_f,
        inNotificationRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMUnshareData(
        inDataName: *const ::std::os::raw::c_char,
        inDataType: XPLMDataTypeID,
        inNotificationFunc: XPLMDataChanged_f,
        inNotificationRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
pub const xplm_Phase_Modern3D: _bindgen_ty_6 = 31;
pub const xplm_Phase_FirstCockpit: _bindgen_ty_6 = 35;
pub const xplm_Phase_Panel: _bindgen_ty_6 = 40;
pub const xplm_Phase_Gauges: _bindgen_ty_6 = 45;
pub const xplm_Phase_Window: _bindgen_ty_6 = 50;
pub const xplm_Phase_LastCockpit: _bindgen_ty_6 = 55;
pub const xplm_Phase_LocalMap3D: _bindgen_ty_6 = 100;
pub const xplm_Phase_LocalMap2D: _bindgen_ty_6 = 101;
pub const xplm_Phase_LocalMapProfile: _bindgen_ty_6 = 102;
pub type _bindgen_ty_6 = ::std::os::raw::c_uint;
pub type XPLMDrawingPhase = ::std::os::raw::c_int;
pub type XPLMDrawCallback_f = ::std::option::Option<
    unsafe extern "C" fn(
        inPhase: XPLMDrawingPhase,
        inIsBefore: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn XPLMRegisterDrawCallback(
        inCallback: XPLMDrawCallback_f,
        inPhase: XPLMDrawingPhase,
        inWantsBefore: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMUnregisterDrawCallback(
        inCallback: XPLMDrawCallback_f,
        inPhase: XPLMDrawingPhase,
        inWantsBefore: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
pub const xplm_device_GNS430_1: _bindgen_ty_7 = 0;
pub const xplm_device_GNS430_2: _bindgen_ty_7 = 1;
pub const xplm_device_GNS530_1: _bindgen_ty_7 = 2;
pub const xplm_device_GNS530_2: _bindgen_ty_7 = 3;
pub const xplm_device_CDU739_1: _bindgen_ty_7 = 4;
pub const xplm_device_CDU739_2: _bindgen_ty_7 = 5;
pub const xplm_device_G1000_PFD_1: _bindgen_ty_7 = 6;
pub const xplm_device_G1000_MFD: _bindgen_ty_7 = 7;
pub const xplm_device_G1000_PFD_2: _bindgen_ty_7 = 8;
pub const xplm_device_CDU815_1: _bindgen_ty_7 = 9;
pub const xplm_device_CDU815_2: _bindgen_ty_7 = 10;
pub const xplm_device_Primus_PFD_1: _bindgen_ty_7 = 11;
pub const xplm_device_Primus_PFD_2: _bindgen_ty_7 = 12;
pub const xplm_device_Primus_MFD_1: _bindgen_ty_7 = 13;
pub const xplm_device_Primus_MFD_2: _bindgen_ty_7 = 14;
pub const xplm_device_Primus_MFD_3: _bindgen_ty_7 = 15;
pub const xplm_device_Primus_RMU_1: _bindgen_ty_7 = 16;
pub const xplm_device_Primus_RMU_2: _bindgen_ty_7 = 17;
pub const xplm_device_MCDU_1: _bindgen_ty_7 = 18;
pub const xplm_device_MCDU_2: _bindgen_ty_7 = 19;
pub const xplm_device_MCDU_3: _bindgen_ty_7 = 24;
pub type _bindgen_ty_7 = ::std::os::raw::c_uint;
pub type XPLMDeviceID = ::std::os::raw::c_int;
pub type XPLMAvionicsCallback_f = ::std::option::Option<
    unsafe extern "C" fn(
        inDeviceID: XPLMDeviceID,
        inIsBefore: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMAvionicsMouse_f = ::std::option::Option<
    unsafe extern "C" fn(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        inMouse: XPLMMouseStatus,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMAvionicsMouseWheel_f = ::std::option::Option<
    unsafe extern "C" fn(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        wheel: ::std::os::raw::c_int,
        clicks: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMAvionicsCursor_f = ::std::option::Option<
    unsafe extern "C" fn(
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> XPLMCursorStatus,
>;
pub type XPLMAvionicsKeyboard_f = ::std::option::Option<
    unsafe extern "C" fn(
        inKey: ::std::os::raw::c_char,
        inFlags: XPLMKeyFlags,
        inVirtualKey: ::std::os::raw::c_char,
        inRefCon: *mut ::std::os::raw::c_void,
        losingFocus: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMAvionicsID = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMCustomizeAvionics_t {
    pub structSize: ::std::os::raw::c_int,
    pub deviceId: XPLMDeviceID,
    pub drawCallbackBefore: XPLMAvionicsCallback_f,
    pub drawCallbackAfter: XPLMAvionicsCallback_f,
    pub bezelClickCallback: XPLMAvionicsMouse_f,
    pub bezelRightClickCallback: XPLMAvionicsMouse_f,
    pub bezelScrollCallback: XPLMAvionicsMouseWheel_f,
    pub bezelCursorCallback: XPLMAvionicsCursor_f,
    pub screenTouchCallback: XPLMAvionicsMouse_f,
    pub screenRightTouchCallback: XPLMAvionicsMouse_f,
    pub screenScrollCallback: XPLMAvionicsMouseWheel_f,
    pub screenCursorCallback: XPLMAvionicsCursor_f,
    pub keyboardCallback: XPLMAvionicsKeyboard_f,
    pub refcon: *mut ::std::os::raw::c_void,
}
unsafe extern "C" {
    pub fn XPLMRegisterAvionicsCallbacksEx(
        inParams: *mut XPLMCustomizeAvionics_t,
    ) -> XPLMAvionicsID;
}
unsafe extern "C" {
    pub fn XPLMGetAvionicsHandle(inDeviceID: XPLMDeviceID) -> XPLMAvionicsID;
}
unsafe extern "C" {
    pub fn XPLMUnregisterAvionicsCallbacks(inAvionicsId: XPLMAvionicsID);
}
pub type XPLMAvionicsScreenCallback_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void)>;
pub type XPLMAvionicsBezelCallback_f = ::std::option::Option<
    unsafe extern "C" fn(
        inAmbiantR: f32,
        inAmbiantG: f32,
        inAmbiantB: f32,
        inRefcon: *mut ::std::os::raw::c_void,
    ),
>;
pub type XPLMAvionicsBrightness_f = ::std::option::Option<
    unsafe extern "C" fn(
        inRheoValue: f32,
        inAmbiantBrightness: f32,
        inBusVoltsRatio: f32,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> f32,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMCreateAvionics_t {
    pub structSize: ::std::os::raw::c_int,
    pub screenWidth: ::std::os::raw::c_int,
    pub screenHeight: ::std::os::raw::c_int,
    pub bezelWidth: ::std::os::raw::c_int,
    pub bezelHeight: ::std::os::raw::c_int,
    pub screenOffsetX: ::std::os::raw::c_int,
    pub screenOffsetY: ::std::os::raw::c_int,
    pub drawOnDemand: ::std::os::raw::c_int,
    pub bezelDrawCallback: XPLMAvionicsBezelCallback_f,
    pub drawCallback: XPLMAvionicsScreenCallback_f,
    pub bezelClickCallback: XPLMAvionicsMouse_f,
    pub bezelRightClickCallback: XPLMAvionicsMouse_f,
    pub bezelScrollCallback: XPLMAvionicsMouseWheel_f,
    pub bezelCursorCallback: XPLMAvionicsCursor_f,
    pub screenTouchCallback: XPLMAvionicsMouse_f,
    pub screenRightTouchCallback: XPLMAvionicsMouse_f,
    pub screenScrollCallback: XPLMAvionicsMouseWheel_f,
    pub screenCursorCallback: XPLMAvionicsCursor_f,
    pub keyboardCallback: XPLMAvionicsKeyboard_f,
    pub brightnessCallback: XPLMAvionicsBrightness_f,
    pub deviceID: *mut ::std::os::raw::c_char,
    pub deviceName: *mut ::std::os::raw::c_char,
    pub refcon: *mut ::std::os::raw::c_void,
}
unsafe extern "C" {
    pub fn XPLMCreateAvionicsEx(inParams: *mut XPLMCreateAvionics_t) -> XPLMAvionicsID;
}
unsafe extern "C" {
    pub fn XPLMDestroyAvionics(inHandle: XPLMAvionicsID);
}
unsafe extern "C" {
    pub fn XPLMIsAvionicsBound(inHandle: XPLMAvionicsID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSetAvionicsBrightnessRheo(inHandle: XPLMAvionicsID, brightness: f32);
}
unsafe extern "C" {
    pub fn XPLMGetAvionicsBrightnessRheo(inHandle: XPLMAvionicsID) -> f32;
}
unsafe extern "C" {
    pub fn XPLMGetAvionicsBusVoltsRatio(inHandle: XPLMAvionicsID) -> f32;
}
unsafe extern "C" {
    pub fn XPLMIsCursorOverAvionics(
        inHandle: XPLMAvionicsID,
        outX: *mut ::std::os::raw::c_int,
        outY: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMAvionicsNeedsDrawing(inHandle: XPLMAvionicsID);
}
unsafe extern "C" {
    pub fn XPLMSetAvionicsPopupVisible(inHandle: XPLMAvionicsID, inVisible: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn XPLMIsAvionicsPopupVisible(inHandle: XPLMAvionicsID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMPopOutAvionics(inHandle: XPLMAvionicsID);
}
unsafe extern "C" {
    pub fn XPLMIsAvionicsPoppedOut(inHandle: XPLMAvionicsID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMTakeAvionicsKeyboardFocus(inHandle: XPLMAvionicsID);
}
unsafe extern "C" {
    pub fn XPLMHasAvionicsKeyboardFocus(inHandle: XPLMAvionicsID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMGetAvionicsGeometry(
        inHandle: XPLMAvionicsID,
        outLeft: *mut ::std::os::raw::c_int,
        outTop: *mut ::std::os::raw::c_int,
        outRight: *mut ::std::os::raw::c_int,
        outBottom: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMSetAvionicsGeometry(
        inHandle: XPLMAvionicsID,
        inLeft: ::std::os::raw::c_int,
        inTop: ::std::os::raw::c_int,
        inRight: ::std::os::raw::c_int,
        inBottom: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetAvionicsGeometryOS(
        inHandle: XPLMAvionicsID,
        outLeft: *mut ::std::os::raw::c_int,
        outTop: *mut ::std::os::raw::c_int,
        outRight: *mut ::std::os::raw::c_int,
        outBottom: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMSetAvionicsGeometryOS(
        inHandle: XPLMAvionicsID,
        inLeft: ::std::os::raw::c_int,
        inTop: ::std::os::raw::c_int,
        inRight: ::std::os::raw::c_int,
        inBottom: ::std::os::raw::c_int,
    );
}
pub type XPLMWindowID = *mut ::std::os::raw::c_void;
pub type XPLMDrawWindow_f = ::std::option::Option<
    unsafe extern "C" fn(inWindowID: XPLMWindowID, inRefcon: *mut ::std::os::raw::c_void),
>;
pub type XPLMHandleKey_f = ::std::option::Option<
    unsafe extern "C" fn(
        inWindowID: XPLMWindowID,
        inKey: ::std::os::raw::c_char,
        inFlags: XPLMKeyFlags,
        inVirtualKey: ::std::os::raw::c_char,
        inRefcon: *mut ::std::os::raw::c_void,
        losingFocus: ::std::os::raw::c_int,
    ),
>;
pub type XPLMHandleMouseClick_f = ::std::option::Option<
    unsafe extern "C" fn(
        inWindowID: XPLMWindowID,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        inMouse: XPLMMouseStatus,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub type XPLMHandleCursor_f = ::std::option::Option<
    unsafe extern "C" fn(
        inWindowID: XPLMWindowID,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> XPLMCursorStatus,
>;
pub type XPLMHandleMouseWheel_f = ::std::option::Option<
    unsafe extern "C" fn(
        inWindowID: XPLMWindowID,
        x: ::std::os::raw::c_int,
        y: ::std::os::raw::c_int,
        wheel: ::std::os::raw::c_int,
        clicks: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
pub const xplm_WindowLayerFlightOverlay: _bindgen_ty_8 = 0;
pub const xplm_WindowLayerFloatingWindows: _bindgen_ty_8 = 1;
pub const xplm_WindowLayerModal: _bindgen_ty_8 = 2;
pub const xplm_WindowLayerGrowlNotifications: _bindgen_ty_8 = 3;
pub type _bindgen_ty_8 = ::std::os::raw::c_uint;
pub type XPLMWindowLayer = ::std::os::raw::c_int;
pub const xplm_WindowDecorationNone: _bindgen_ty_9 = 0;
pub const xplm_WindowDecorationRoundRectangle: _bindgen_ty_9 = 1;
pub const xplm_WindowDecorationSelfDecorated: _bindgen_ty_9 = 2;
pub const xplm_WindowDecorationSelfDecoratedResizable: _bindgen_ty_9 = 3;
pub type _bindgen_ty_9 = ::std::os::raw::c_uint;
pub type XPLMWindowDecoration = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMCreateWindow_t {
    pub structSize: ::std::os::raw::c_int,
    pub left: ::std::os::raw::c_int,
    pub top: ::std::os::raw::c_int,
    pub right: ::std::os::raw::c_int,
    pub bottom: ::std::os::raw::c_int,
    pub visible: ::std::os::raw::c_int,
    pub drawWindowFunc: XPLMDrawWindow_f,
    pub handleMouseClickFunc: XPLMHandleMouseClick_f,
    pub handleKeyFunc: XPLMHandleKey_f,
    pub handleCursorFunc: XPLMHandleCursor_f,
    pub handleMouseWheelFunc: XPLMHandleMouseWheel_f,
    pub refcon: *mut ::std::os::raw::c_void,
    pub decorateAsFloatingWindow: XPLMWindowDecoration,
    pub layer: XPLMWindowLayer,
    pub handleRightClickFunc: XPLMHandleMouseClick_f,
}
unsafe extern "C" {
    pub fn XPLMCreateWindowEx(inParams: *mut XPLMCreateWindow_t) -> XPLMWindowID;
}
unsafe extern "C" {
    pub fn XPLMCreateWindow(
        inLeft: ::std::os::raw::c_int,
        inTop: ::std::os::raw::c_int,
        inRight: ::std::os::raw::c_int,
        inBottom: ::std::os::raw::c_int,
        inIsVisible: ::std::os::raw::c_int,
        inDrawCallback: XPLMDrawWindow_f,
        inKeyCallback: XPLMHandleKey_f,
        inMouseCallback: XPLMHandleMouseClick_f,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> XPLMWindowID;
}
unsafe extern "C" {
    pub fn XPLMDestroyWindow(inWindowID: XPLMWindowID);
}
unsafe extern "C" {
    pub fn XPLMGetScreenSize(
        outWidth: *mut ::std::os::raw::c_int,
        outHeight: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetScreenBoundsGlobal(
        outLeft: *mut ::std::os::raw::c_int,
        outTop: *mut ::std::os::raw::c_int,
        outRight: *mut ::std::os::raw::c_int,
        outBottom: *mut ::std::os::raw::c_int,
    );
}
pub type XPLMReceiveMonitorBoundsGlobal_f = ::std::option::Option<
    unsafe extern "C" fn(
        inMonitorIndex: ::std::os::raw::c_int,
        inLeftBx: ::std::os::raw::c_int,
        inTopBx: ::std::os::raw::c_int,
        inRightBx: ::std::os::raw::c_int,
        inBottomBx: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn XPLMGetAllMonitorBoundsGlobal(
        inMonitorBoundsCallback: XPLMReceiveMonitorBoundsGlobal_f,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
pub type XPLMReceiveMonitorBoundsOS_f = ::std::option::Option<
    unsafe extern "C" fn(
        inMonitorIndex: ::std::os::raw::c_int,
        inLeftPx: ::std::os::raw::c_int,
        inTopPx: ::std::os::raw::c_int,
        inRightPx: ::std::os::raw::c_int,
        inBottomPx: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn XPLMGetAllMonitorBoundsOS(
        inMonitorBoundsCallback: XPLMReceiveMonitorBoundsOS_f,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn XPLMGetMouseLocation(outX: *mut ::std::os::raw::c_int, outY: *mut ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn XPLMGetMouseLocationGlobal(
        outX: *mut ::std::os::raw::c_int,
        outY: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetWindowGeometry(
        inWindowID: XPLMWindowID,
        outLeft: *mut ::std::os::raw::c_int,
        outTop: *mut ::std::os::raw::c_int,
        outRight: *mut ::std::os::raw::c_int,
        outBottom: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMSetWindowGeometry(
        inWindowID: XPLMWindowID,
        inLeft: ::std::os::raw::c_int,
        inTop: ::std::os::raw::c_int,
        inRight: ::std::os::raw::c_int,
        inBottom: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetWindowGeometryOS(
        inWindowID: XPLMWindowID,
        outLeft: *mut ::std::os::raw::c_int,
        outTop: *mut ::std::os::raw::c_int,
        outRight: *mut ::std::os::raw::c_int,
        outBottom: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMSetWindowGeometryOS(
        inWindowID: XPLMWindowID,
        inLeft: ::std::os::raw::c_int,
        inTop: ::std::os::raw::c_int,
        inRight: ::std::os::raw::c_int,
        inBottom: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetWindowGeometryVR(
        inWindowID: XPLMWindowID,
        outWidthBoxels: *mut ::std::os::raw::c_int,
        outHeightBoxels: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMSetWindowGeometryVR(
        inWindowID: XPLMWindowID,
        widthBoxels: ::std::os::raw::c_int,
        heightBoxels: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetWindowIsVisible(inWindowID: XPLMWindowID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSetWindowIsVisible(inWindowID: XPLMWindowID, inIsVisible: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn XPLMWindowIsPoppedOut(inWindowID: XPLMWindowID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMWindowIsInVR(inWindowID: XPLMWindowID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSetWindowGravity(
        inWindowID: XPLMWindowID,
        inLeftGravity: f32,
        inTopGravity: f32,
        inRightGravity: f32,
        inBottomGravity: f32,
    );
}
unsafe extern "C" {
    pub fn XPLMSetWindowResizingLimits(
        inWindowID: XPLMWindowID,
        inMinWidthBoxels: ::std::os::raw::c_int,
        inMinHeightBoxels: ::std::os::raw::c_int,
        inMaxWidthBoxels: ::std::os::raw::c_int,
        inMaxHeightBoxels: ::std::os::raw::c_int,
    );
}
pub const xplm_WindowPositionFree: _bindgen_ty_10 = 0;
pub const xplm_WindowCenterOnMonitor: _bindgen_ty_10 = 1;
pub const xplm_WindowFullScreenOnMonitor: _bindgen_ty_10 = 2;
pub const xplm_WindowFullScreenOnAllMonitors: _bindgen_ty_10 = 3;
pub const xplm_WindowPopOut: _bindgen_ty_10 = 4;
pub const xplm_WindowVR: _bindgen_ty_10 = 5;
pub type _bindgen_ty_10 = ::std::os::raw::c_uint;
pub type XPLMWindowPositioningMode = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn XPLMSetWindowPositioningMode(
        inWindowID: XPLMWindowID,
        inPositioningMode: XPLMWindowPositioningMode,
        inMonitorIndex: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMSetWindowTitle(
        inWindowID: XPLMWindowID,
        inWindowTitle: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn XPLMGetWindowRefCon(inWindowID: XPLMWindowID) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn XPLMSetWindowRefCon(inWindowID: XPLMWindowID, inRefcon: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn XPLMTakeKeyboardFocus(inWindow: XPLMWindowID);
}
unsafe extern "C" {
    pub fn XPLMHasKeyboardFocus(inWindow: XPLMWindowID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMBringWindowToFront(inWindow: XPLMWindowID);
}
unsafe extern "C" {
    pub fn XPLMIsWindowInFront(inWindow: XPLMWindowID) -> ::std::os::raw::c_int;
}
pub type XPLMKeySniffer_f = ::std::option::Option<
    unsafe extern "C" fn(
        inChar: ::std::os::raw::c_char,
        inFlags: XPLMKeyFlags,
        inVirtualKey: ::std::os::raw::c_char,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn XPLMRegisterKeySniffer(
        inCallback: XPLMKeySniffer_f,
        inBeforeWindows: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMUnregisterKeySniffer(
        inCallback: XPLMKeySniffer_f,
        inBeforeWindows: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
pub type XPLMHotKey_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void)>;
pub type XPLMHotKeyID = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn XPLMRegisterHotKey(
        inVirtualKey: ::std::os::raw::c_char,
        inFlags: XPLMKeyFlags,
        inDescription: *const ::std::os::raw::c_char,
        inCallback: XPLMHotKey_f,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> XPLMHotKeyID;
}
unsafe extern "C" {
    pub fn XPLMUnregisterHotKey(inHotKey: XPLMHotKeyID);
}
unsafe extern "C" {
    pub fn XPLMCountHotKeys() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMGetNthHotKey(inIndex: ::std::os::raw::c_int) -> XPLMHotKeyID;
}
unsafe extern "C" {
    pub fn XPLMGetHotKeyInfo(
        inHotKey: XPLMHotKeyID,
        outVirtualKey: *mut ::std::os::raw::c_char,
        outFlags: *mut XPLMKeyFlags,
        outDescription: *mut ::std::os::raw::c_char,
        outPlugin: *mut XPLMPluginID,
    );
}
unsafe extern "C" {
    pub fn XPLMSetHotKeyCombination(
        inHotKey: XPLMHotKeyID,
        inVirtualKey: ::std::os::raw::c_char,
        inFlags: XPLMKeyFlags,
    );
}
pub const xplm_Tex_GeneralInterface: _bindgen_ty_11 = 0;
pub const xplm_Tex_Radar_Pilot: _bindgen_ty_11 = 3;
pub const xplm_Tex_Radar_Copilot: _bindgen_ty_11 = 4;
pub type _bindgen_ty_11 = ::std::os::raw::c_uint;
pub type XPLMTextureID = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn XPLMSetGraphicsState(
        inEnableFog: ::std::os::raw::c_int,
        inNumberTexUnits: ::std::os::raw::c_int,
        inEnableLighting: ::std::os::raw::c_int,
        inEnableAlphaTesting: ::std::os::raw::c_int,
        inEnableAlphaBlending: ::std::os::raw::c_int,
        inEnableDepthTesting: ::std::os::raw::c_int,
        inEnableDepthWriting: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMBindTexture2d(
        inTextureNum: ::std::os::raw::c_int,
        inTextureUnit: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGenerateTextureNumbers(
        outTextureIDs: *mut ::std::os::raw::c_int,
        inCount: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMGetTexture(inTexture: XPLMTextureID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMWorldToLocal(
        inLatitude: f64,
        inLongitude: f64,
        inAltitude: f64,
        outX: *mut f64,
        outY: *mut f64,
        outZ: *mut f64,
    );
}
unsafe extern "C" {
    pub fn XPLMLocalToWorld(
        inX: f64,
        inY: f64,
        inZ: f64,
        outLatitude: *mut f64,
        outLongitude: *mut f64,
        outAltitude: *mut f64,
    );
}
unsafe extern "C" {
    pub fn XPLMDrawTranslucentDarkBox(
        inLeft: ::std::os::raw::c_int,
        inTop: ::std::os::raw::c_int,
        inRight: ::std::os::raw::c_int,
        inBottom: ::std::os::raw::c_int,
    );
}
pub type XPLMFontID = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn XPLMDrawString(
        inColorRGB: *mut f32,
        inXOffset: ::std::os::raw::c_int,
        inYOffset: ::std::os::raw::c_int,
        inChar: *const ::std::os::raw::c_char,
        inWordWrapWidth: *mut ::std::os::raw::c_int,
        inFontID: XPLMFontID,
    );
}
unsafe extern "C" {
    pub fn XPLMDrawNumber(
        inColorRGB: *mut f32,
        inXOffset: ::std::os::raw::c_int,
        inYOffset: ::std::os::raw::c_int,
        inValue: f64,
        inDigits: ::std::os::raw::c_int,
        inDecimals: ::std::os::raw::c_int,
        inShowSign: ::std::os::raw::c_int,
        inFontID: XPLMFontID,
    );
}
unsafe extern "C" {
    pub fn XPLMGetFontDimensions(
        inFontID: XPLMFontID,
        outCharWidth: *mut ::std::os::raw::c_int,
        outCharHeight: *mut ::std::os::raw::c_int,
        outDigitsOnly: *mut ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMMeasureString(
        inFontID: XPLMFontID,
        inChar: *const ::std::os::raw::c_char,
        inNumChars: ::std::os::raw::c_int,
    ) -> f32;
}
pub const xplm_DataFile_Situation: _bindgen_ty_13 = 1;
pub const xplm_DataFile_ReplayMovie: _bindgen_ty_13 = 2;
pub type _bindgen_ty_13 = ::std::os::raw::c_uint;
pub type XPLMDataFileType = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn XPLMGetSystemPath(outSystemPath: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn XPLMGetPrefsPath(outPrefsPath: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn XPLMGetDirectorySeparator() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn XPLMExtractFileAndPath(
        inFullPath: *mut ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn XPLMGetDirectoryContents(
        inDirectoryPath: *const ::std::os::raw::c_char,
        inFirstReturn: ::std::os::raw::c_int,
        outFileNames: *mut ::std::os::raw::c_char,
        inFileNameBufSize: ::std::os::raw::c_int,
        outIndices: *mut *mut ::std::os::raw::c_char,
        inIndexCount: ::std::os::raw::c_int,
        outTotalFiles: *mut ::std::os::raw::c_int,
        outReturnedFiles: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMLoadDataFile(
        inFileType: XPLMDataFileType,
        inFilePath: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMSaveDataFile(
        inFileType: XPLMDataFileType,
        inFilePath: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
pub const xplm_Host_Unknown: _bindgen_ty_14 = 0;
pub const xplm_Host_XPlane: _bindgen_ty_14 = 1;
pub type _bindgen_ty_14 = ::std::os::raw::c_uint;
pub type XPLMHostApplicationID = ::std::os::raw::c_int;
pub const xplm_Language_Unknown: _bindgen_ty_15 = 0;
pub const xplm_Language_English: _bindgen_ty_15 = 1;
pub const xplm_Language_French: _bindgen_ty_15 = 2;
pub const xplm_Language_German: _bindgen_ty_15 = 3;
pub const xplm_Language_Italian: _bindgen_ty_15 = 4;
pub const xplm_Language_Spanish: _bindgen_ty_15 = 5;
pub const xplm_Language_Korean: _bindgen_ty_15 = 6;
pub const xplm_Language_Russian: _bindgen_ty_15 = 7;
pub const xplm_Language_Greek: _bindgen_ty_15 = 8;
pub const xplm_Language_Japanese: _bindgen_ty_15 = 9;
pub const xplm_Language_Chinese: _bindgen_ty_15 = 10;
pub const xplm_Language_Ukrainian: _bindgen_ty_15 = 11;
pub type _bindgen_ty_15 = ::std::os::raw::c_uint;
pub type XPLMLanguageCode = ::std::os::raw::c_int;
pub type XPLMError_f =
    ::std::option::Option<unsafe extern "C" fn(inMessage: *const ::std::os::raw::c_char)>;
unsafe extern "C" {
    pub fn XPLMGetVersions(
        outXPlaneVersion: *mut ::std::os::raw::c_int,
        outXPLMVersion: *mut ::std::os::raw::c_int,
        outHostID: *mut XPLMHostApplicationID,
    );
}
unsafe extern "C" {
    pub fn XPLMGetLanguage() -> XPLMLanguageCode;
}
unsafe extern "C" {
    pub fn XPLMFindSymbol(inString: *const ::std::os::raw::c_char) -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn XPLMSetErrorCallback(inCallback: XPLMError_f);
}
unsafe extern "C" {
    pub fn XPLMDebugString(inString: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn XPLMSpeakString(inString: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn XPLMGetVirtualKeyDescription(
        inVirtualKey: ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn XPLMReloadScenery();
}
pub const xplm_CommandBegin: _bindgen_ty_16 = 0;
pub const xplm_CommandContinue: _bindgen_ty_16 = 1;
pub const xplm_CommandEnd: _bindgen_ty_16 = 2;
pub type _bindgen_ty_16 = ::std::os::raw::c_uint;
pub type XPLMCommandPhase = ::std::os::raw::c_int;
pub type XPLMCommandRef = *mut ::std::os::raw::c_void;
pub type XPLMCommandCallback_f = ::std::option::Option<
    unsafe extern "C" fn(
        inCommand: XPLMCommandRef,
        inPhase: XPLMCommandPhase,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub fn XPLMFindCommand(inName: *const ::std::os::raw::c_char) -> XPLMCommandRef;
}
unsafe extern "C" {
    pub fn XPLMCommandBegin(inCommand: XPLMCommandRef);
}
unsafe extern "C" {
    pub fn XPLMCommandEnd(inCommand: XPLMCommandRef);
}
unsafe extern "C" {
    pub fn XPLMCommandOnce(inCommand: XPLMCommandRef);
}
unsafe extern "C" {
    pub fn XPLMCreateCommand(
        inName: *const ::std::os::raw::c_char,
        inDescription: *const ::std::os::raw::c_char,
    ) -> XPLMCommandRef;
}
unsafe extern "C" {
    pub fn XPLMRegisterCommandHandler(
        inComand: XPLMCommandRef,
        inHandler: XPLMCommandCallback_f,
        inBefore: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn XPLMUnregisterCommandHandler(
        inComand: XPLMCommandRef,
        inHandler: XPLMCommandCallback_f,
        inBefore: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
pub const xplm_Menu_NoCheck: _bindgen_ty_17 = 0;
pub const xplm_Menu_Unchecked: _bindgen_ty_17 = 1;
pub const xplm_Menu_Checked: _bindgen_ty_17 = 2;
pub type _bindgen_ty_17 = ::std::os::raw::c_uint;
pub type XPLMMenuCheck = ::std::os::raw::c_int;
pub type XPLMMenuID = *mut ::std::os::raw::c_void;
pub type XPLMMenuHandler_f = ::std::option::Option<
    unsafe extern "C" fn(
        inMenuRef: *mut ::std::os::raw::c_void,
        inItemRef: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn XPLMFindPluginsMenu() -> XPLMMenuID;
}
unsafe extern "C" {
    pub fn XPLMFindAircraftMenu() -> XPLMMenuID;
}
unsafe extern "C" {
    pub fn XPLMCreateMenu(
        inName: *const ::std::os::raw::c_char,
        inParentMenu: XPLMMenuID,
        inParentItem: ::std::os::raw::c_int,
        inHandler: XPLMMenuHandler_f,
        inMenuRef: *mut ::std::os::raw::c_void,
    ) -> XPLMMenuID;
}
unsafe extern "C" {
    pub fn XPLMDestroyMenu(inMenuID: XPLMMenuID);
}
unsafe extern "C" {
    pub fn XPLMClearAllMenuItems(inMenuID: XPLMMenuID);
}
unsafe extern "C" {
    pub fn XPLMAppendMenuItem(
        inMenu: XPLMMenuID,
        inItemName: *const ::std::os::raw::c_char,
        inItemRef: *mut ::std::os::raw::c_void,
        inDeprecatedAndIgnored: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMAppendMenuItemWithCommand(
        inMenu: XPLMMenuID,
        inItemName: *const ::std::os::raw::c_char,
        inCommandToExecute: XPLMCommandRef,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMAppendMenuSeparator(inMenu: XPLMMenuID);
}
unsafe extern "C" {
    pub fn XPLMSetMenuItemName(
        inMenu: XPLMMenuID,
        inIndex: ::std::os::raw::c_int,
        inItemName: *const ::std::os::raw::c_char,
        inDeprecatedAndIgnored: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMCheckMenuItem(
        inMenu: XPLMMenuID,
        index: ::std::os::raw::c_int,
        inCheck: XPLMMenuCheck,
    );
}
unsafe extern "C" {
    pub fn XPLMCheckMenuItemState(
        inMenu: XPLMMenuID,
        index: ::std::os::raw::c_int,
        outCheck: *mut XPLMMenuCheck,
    );
}
unsafe extern "C" {
    pub fn XPLMEnableMenuItem(
        inMenu: XPLMMenuID,
        index: ::std::os::raw::c_int,
        enabled: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMRemoveMenuItem(inMenu: XPLMMenuID, inIndex: ::std::os::raw::c_int);
}
pub const xplm_Init_Success: _bindgen_ty_18 = 0;
pub const xplm_Init_Invalid: _bindgen_ty_18 = 1;
pub const xplm_Init_MissingAircraft: _bindgen_ty_18 = 2;
pub const xplm_Init_MissingLivery: _bindgen_ty_18 = 3;
pub const xplm_Init_MissingAirport: _bindgen_ty_18 = 4;
pub const xplm_Init_MissingRamp: _bindgen_ty_18 = 5;
pub const xplm_Init_MissingRunway: _bindgen_ty_18 = 6;
pub type _bindgen_ty_18 = ::std::os::raw::c_uint;
pub type XPLMInitResult = ::std::os::raw::c_int;
unsafe extern "C" {
    pub fn XPLMInitFlight(inJsonData: *const ::std::os::raw::c_char) -> XPLMInitResult;
}
unsafe extern "C" {
    pub fn XPLMUpdateFlight(inJsonData: *const ::std::os::raw::c_char) -> XPLMInitResult;
}
unsafe extern "C" {
    pub fn XPLMSetUsersAircraft(inAircraftPath: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn XPLMPlaceUserAtAirport(inAirportCode: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn XPLMPlaceUserAtLocation(
        latitudeDegrees: f64,
        longitudeDegrees: f64,
        elevationMetersMSL: f32,
        headingDegreesTrue: f32,
        speedMetersPerSecond: f32,
    );
}
unsafe extern "C" {
    pub fn XPLMCountAircraft(
        outTotalAircraft: *mut ::std::os::raw::c_int,
        outActiveAircraft: *mut ::std::os::raw::c_int,
        outController: *mut XPLMPluginID,
    );
}
unsafe extern "C" {
    pub fn XPLMGetNthAircraftModel(
        inIndex: ::std::os::raw::c_int,
        outFileName: *mut ::std::os::raw::c_char,
        outPath: *mut ::std::os::raw::c_char,
    );
}
pub type XPLMPlanesAvailable_f =
    ::std::option::Option<unsafe extern "C" fn(inRefcon: *mut ::std::os::raw::c_void)>;
unsafe extern "C" {
    pub fn XPLMAcquirePlanes(
        inAircraft: *mut *mut ::std::os::raw::c_char,
        inCallback: XPLMPlanesAvailable_f,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMReleasePlanes();
}
unsafe extern "C" {
    pub fn XPLMSetActiveAircraftCount(inCount: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn XPLMSetAircraftModel(
        inIndex: ::std::os::raw::c_int,
        inAircraftPath: *const ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn XPLMDisableAIForPlane(inPlaneIndex: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn XPLMGetMyID() -> XPLMPluginID;
}
unsafe extern "C" {
    pub fn XPLMCountPlugins() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMGetNthPlugin(inIndex: ::std::os::raw::c_int) -> XPLMPluginID;
}
unsafe extern "C" {
    pub fn XPLMFindPluginByPath(inPath: *const ::std::os::raw::c_char) -> XPLMPluginID;
}
unsafe extern "C" {
    pub fn XPLMFindPluginBySignature(inSignature: *const ::std::os::raw::c_char) -> XPLMPluginID;
}
unsafe extern "C" {
    pub fn XPLMGetPluginInfo(
        inPlugin: XPLMPluginID,
        outName: *mut ::std::os::raw::c_char,
        outFilePath: *mut ::std::os::raw::c_char,
        outSignature: *mut ::std::os::raw::c_char,
        outDescription: *mut ::std::os::raw::c_char,
    );
}
unsafe extern "C" {
    pub fn XPLMIsPluginEnabled(inPluginID: XPLMPluginID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMEnablePlugin(inPluginID: XPLMPluginID) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMDisablePlugin(inPluginID: XPLMPluginID);
}
unsafe extern "C" {
    pub fn XPLMReloadPlugins();
}
unsafe extern "C" {
    pub fn XPLMSendMessageToPlugin(
        inPlugin: XPLMPluginID,
        inMessage: ::std::os::raw::c_int,
        inParam: *mut ::std::os::raw::c_void,
    );
}
pub type XPLMFeatureEnumerator_f = ::std::option::Option<
    unsafe extern "C" fn(
        inFeature: *const ::std::os::raw::c_char,
        inRef: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn XPLMHasFeature(inFeature: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMIsFeatureEnabled(inFeature: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMEnableFeature(
        inFeature: *const ::std::os::raw::c_char,
        inEnable: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn XPLMEnumerateFeatures(
        inEnumerator: XPLMFeatureEnumerator_f,
        inRef: *mut ::std::os::raw::c_void,
    );
}
pub const xplm_FlightLoop_Phase_BeforeFlightModel: _bindgen_ty_19 = 0;
pub const xplm_FlightLoop_Phase_AfterFlightModel: _bindgen_ty_19 = 1;
pub type _bindgen_ty_19 = ::std::os::raw::c_uint;
pub type XPLMFlightLoopPhaseType = ::std::os::raw::c_int;
pub type XPLMFlightLoopID = *mut ::std::os::raw::c_void;
pub type XPLMFlightLoop_f = ::std::option::Option<
    unsafe extern "C" fn(
        inElapsedSinceLastCall: f32,
        inElapsedTimeSinceLastFlightLoop: f32,
        inCounter: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    ) -> f32,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMCreateFlightLoop_t {
    pub structSize: ::std::os::raw::c_int,
    pub phase: XPLMFlightLoopPhaseType,
    pub callbackFunc: XPLMFlightLoop_f,
    pub refcon: *mut ::std::os::raw::c_void,
}
unsafe extern "C" {
    pub fn XPLMGetElapsedTime() -> f32;
}
unsafe extern "C" {
    pub fn XPLMGetCycleNumber() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn XPLMRegisterFlightLoopCallback(
        inFlightLoop: XPLMFlightLoop_f,
        inInterval: f32,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn XPLMUnregisterFlightLoopCallback(
        inFlightLoop: XPLMFlightLoop_f,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn XPLMSetFlightLoopCallbackInterval(
        inFlightLoop: XPLMFlightLoop_f,
        inInterval: f32,
        inRelativeToNow: ::std::os::raw::c_int,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn XPLMCreateFlightLoop(inParams: *mut XPLMCreateFlightLoop_t) -> XPLMFlightLoopID;
}
unsafe extern "C" {
    pub fn XPLMDestroyFlightLoop(inFlightLoopID: XPLMFlightLoopID);
}
unsafe extern "C" {
    pub fn XPLMScheduleFlightLoop(
        inFlightLoopID: XPLMFlightLoopID,
        inInterval: f32,
        inRelativeToNow: ::std::os::raw::c_int,
    );
}
pub const xplm_ProbeY: _bindgen_ty_20 = 0;
pub type _bindgen_ty_20 = ::std::os::raw::c_uint;
pub type XPLMProbeType = ::std::os::raw::c_int;
pub const xplm_ProbeHitTerrain: _bindgen_ty_21 = 0;
pub const xplm_ProbeError: _bindgen_ty_21 = 1;
pub const xplm_ProbeMissed: _bindgen_ty_21 = 2;
pub type _bindgen_ty_21 = ::std::os::raw::c_uint;
pub type XPLMProbeResult = ::std::os::raw::c_int;
pub type XPLMProbeRef = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMProbeInfo_t {
    pub structSize: ::std::os::raw::c_int,
    pub locationX: f32,
    pub locationY: f32,
    pub locationZ: f32,
    pub normalX: f32,
    pub normalY: f32,
    pub normalZ: f32,
    pub velocityX: f32,
    pub velocityY: f32,
    pub velocityZ: f32,
    pub is_wet: ::std::os::raw::c_int,
}
unsafe extern "C" {
    pub fn XPLMCreateProbe(inProbeType: XPLMProbeType) -> XPLMProbeRef;
}
unsafe extern "C" {
    pub fn XPLMDestroyProbe(inProbe: XPLMProbeRef);
}
unsafe extern "C" {
    pub fn XPLMProbeTerrainXYZ(
        inProbe: XPLMProbeRef,
        inX: f32,
        inY: f32,
        inZ: f32,
        outInfo: *mut XPLMProbeInfo_t,
    ) -> XPLMProbeResult;
}
unsafe extern "C" {
    pub fn XPLMGetMagneticVariation(latitude: f64, longitude: f64) -> f32;
}
unsafe extern "C" {
    pub fn XPLMDegTrueToDegMagnetic(headingDegreesTrue: f32) -> f32;
}
unsafe extern "C" {
    pub fn XPLMDegMagneticToDegTrue(headingDegreesMagnetic: f32) -> f32;
}
pub type XPLMObjectRef = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMDrawInfo_t {
    pub structSize: ::std::os::raw::c_int,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub pitch: f32,
    pub heading: f32,
    pub roll: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct XPLMDrawInfoDouble_t {
    pub structSize: ::std::os::raw::c_int,
    pub x: f64,
    pub y: f64,
    pub z: f64,
    pub pitch: f64,
    pub heading: f64,
    pub roll: f64,
}
pub type XPLMObjectLoaded_f = ::std::option::Option<
    unsafe extern "C" fn(inObject: XPLMObjectRef, inRefcon: *mut ::std::os::raw::c_void),
>;
unsafe extern "C" {
    pub fn XPLMLoadObject(inPath: *const ::std::os::raw::c_char) -> XPLMObjectRef;
}
unsafe extern "C" {
    pub fn XPLMLoadObjectAsync(
        inPath: *const ::std::os::raw::c_char,
        inCallback: XPLMObjectLoaded_f,
        inRefcon: *mut ::std::os::raw::c_void,
    );
}
unsafe extern "C" {
    pub fn XPLMUnloadObject(inObject: XPLMObjectRef);
}
pub type XPLMLibraryEnumerator_f = ::std::option::Option<
    unsafe extern "C" fn(
        inFilePath: *const ::std::os::raw::c_char,
        inRef: *mut ::std::os::raw::c_void,
    ),
>;
unsafe extern "C" {
    pub fn XPLMLookupObjects(
        inPath: *const ::std::os::raw::c_char,
        inLatitude: f32,
        inLongitude: f32,
        enumerator: XPLMLibraryEnumerator_f,
        ref_: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
