# Link the C runtime statically on Windows so the plugin does not depend on
# the Visual C++ redistributable being installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
