#!/usr/bin/env bash
# Regenerates crates/flyx-xplm/src/sys.rs from the vendored X-Plane SDK headers.
# Needs bindgen-cli (`cargo install bindgen-cli --locked`) and libclang
# (on Windows, set LIBCLANG_PATH, for example to C:/msys64/ucrt64/bin).
#
# The bindings are generated for the Linux target so they never pull in
# <windows.h>. The XPLM headers use only fixed-size and pointer types, so the
# result is valid on every 64-bit platform the plugin supports.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
sdk="${FLYX_XPLANE_SDK:-$root/third_party/xplane-sdk}"
out="$root/crates/flyx-xplm/src/sys.rs"

defines=()
for v in 200 210 300 301 302 303 400 410 420 430; do
  defines+=("-DXPLM$v=1")
done

bindgen "$root/crates/flyx-xplm/wrapper.h" \
  --rust-target 1.89 \
  --no-layout-tests \
  --no-doc-comments \
  --allowlist-function 'XPLM.*' \
  --allowlist-type 'XPLM.*' \
  --allowlist-var 'xplm_.*|kXPLM.*|XPLM_.*' \
  --default-macro-constant-type signed \
  --raw-line '// Generated by scripts/gen-bindings.sh from X-Plane SDK 4.3.0. Do not edit.' \
  --raw-line '#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code, clippy::all)]' \
  -o "$out" \
  -- \
  --target=x86_64-unknown-linux-gnu \
  -DLIN=1 "${defines[@]}" \
  -I "$sdk/CHeaders/XPLM"

echo "wrote $out"
